name: CI
on:
  push:
    branches:
      - master
  create:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - run: yarn install
      - run: yarn build
      - name: Deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build --prod --message='${{ github.event.head_commit.message }}'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Deploy production
        if: startsWith(github.ref, 'refs/tags/v')
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build --prod --message="${{ github.event.head_commit.message }}"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PRODUCTION_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
