name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - run: yarn install
      - run: yarn build
      - name: Deploy production
        if: startsWith(github.ref, 'refs/tags/v')
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: build
          GH_PAT: ${{ secrets.GH_PAT }}
