on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 12
      - run: yarn build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 12
      - uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: build
        secrets:
          - GH_PAT
