name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
      - run: pnpm typecheck
      - run: pnpm lint:ci
      - run: pnpm check-format
      - run: pnpm build
